In [6]:
import pandas as pd
df = pd.read_csv('../data/data_after_1a.csv')
df.head()

,Religion,foolishness,hath,wholesome,takest,feelings,anger,vaivaswata,matrix,kindled,...,erred,thinkest,modern,reigned,sparingly,visual,thoughts,illumines,attire,explains
0,Buddhism,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Buddhism,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Buddhism,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Buddhism,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Buddhism,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
from sklearn.feature_extraction.text import TfidfTransformer

In [8]:
# Initialize
tfidf_trans = TfidfTransformer(smooth_idf=True, use_idf=True, norm='l2')

# convert data in right format
dtm_arr = df.as_matrix(columns=df.columns[1:])

# fit to tfidf
tfidf_trans.fit(dtm_arr)

# calculate tdidf matrix
dtm_arr = df.as_matrix(columns=df.columns[1:])
tf_idf_vector = tfidf_trans.transform(dtm_arr)

/home/thealpha/.local/lib/python3.6/site-packages/ipykernel_launcher.py:5: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """
/home/thealpha/.local/lib/python3.6/site-packages/ipykernel_launcher.py:11: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  # This is added back by InteractiveShellApp.init_path()

In [9]:
# save tfidf as a pickle
import pickle

with open('../data/tdidf_vector.pkl', 'wb') as f_open:
    pickle.dump(tf_idf_vector, f_open)